package loom

import (
	"context"
	"testing"

	"github.com/slack-go/slack"
	"github.com/slack-go/slack/slackevents"
	"github.com/slack-go/slack/socketmode"
)

const testBotID = "U07BOT"

// === translate: Events API ==================================================

func mentionEvent(team, channel, user, text, ts, threadTS, botID string) socketmode.Event {
	return socketmode.Event{
		Type: socketmode.EventTypeEventsAPI,
		Data: slackevents.EventsAPIEvent{
			TeamID: team,
			InnerEvent: slackevents.EventsAPIInnerEvent{
				Data: &slackevents.AppMentionEvent{
					User:            user,
					Text:            text,
					TimeStamp:       ts,
					ThreadTimeStamp: threadTS,
					Channel:         channel,
					BotID:           botID,
				},
			},
		},
	}
}

func TestTranslate_Mention(t *testing.T) {
	evt := mentionEvent("T1", "C1", "U_ALICE", "<@U07BOT> deploy staging", "111.1", "", "")
	got, ok := translate(evt, testBotID)
	if !ok {
		t.Fatal("mention should be handled")
	}
	if got.Kind != KindMention {
		t.Errorf("Kind = %v, want mention", got.Kind)
	}
	if got.Text != "deploy staging" {
		t.Errorf("Text = %q, want %q (mention token should be stripped)", got.Text, "deploy staging")
	}
	if got.Context.Channel != "C1" || got.Context.User != "U_ALICE" || got.Context.Workspace != "T1" {
		t.Errorf("Context = %+v, want C1/U_ALICE/T1", got.Context)
	}
	if got.Timestamp != "111.1" {
		t.Errorf("Timestamp = %q, want 111.1", got.Timestamp)
	}
	if got.Context.Bot != testBotID {
		t.Errorf("Context.Bot = %q, want %q", got.Context.Bot, testBotID)
	}
}

func TestTranslate_MentionInThread(t *testing.T) {
	evt := mentionEvent("T1", "C1", "U_ALICE", "<@U07BOT> hi", "222.2", "100.0", "")
	got, ok := translate(evt, testBotID)
	if !ok {
		t.Fatal("threaded mention should be handled")
	}
	if got.Context.Thread != "100.0" {
		t.Errorf("Thread = %q, want 100.0", got.Context.Thread)
	}
}

func TestTranslate_IgnoresBotMention(t *testing.T) {
	// A mention generated by a bot (BotID set) must be ignored to avoid loops.
	evt := mentionEvent("T1", "C1", "U_OTHER", "<@U07BOT> hi", "1.1", "", "B_SOMEBOT")
	if _, ok := translate(evt, testBotID); ok {
		t.Error("bot-generated mention should be ignored")
	}
}

func TestTranslate_IgnoresSelfMention(t *testing.T) {
	// A mention whose author is the bot itself must be ignored.
	evt := mentionEvent("T1", "C1", testBotID, "<@U07BOT> hi", "1.1", "", "")
	if _, ok := translate(evt, testBotID); ok {
		t.Error("self-authored mention should be ignored")
	}
}

func messageEvent(team, channel, user, text, ts, subtype, botID string) socketmode.Event {
	return socketmode.Event{
		Type: socketmode.EventTypeEventsAPI,
		Data: slackevents.EventsAPIEvent{
			TeamID: team,
			InnerEvent: slackevents.EventsAPIInnerEvent{
				Data: &slackevents.MessageEvent{
					User:      user,
					Text:      text,
					TimeStamp: ts,
					Channel:   channel,
					SubType:   subtype,
					BotID:     botID,
				},
			},
		},
	}
}

func TestTranslate_Message(t *testing.T) {
	evt := messageEvent("T1", "C1", "U_ALICE", "hello", "333.3", "", "")
	got, ok := translate(evt, testBotID)
	if !ok {
		t.Fatal("plain message should be handled")
	}
	if got.Kind != KindMessage {
		t.Errorf("Kind = %v, want message", got.Kind)
	}
	if got.Text != "hello" {
		t.Errorf("Text = %q, want hello", got.Text)
	}
}

func TestTranslate_IgnoresMessageSubtypes(t *testing.T) {
	// Edits/deletes/joins carry a SubType and should be ignored.
	evt := messageEvent("T1", "C1", "U_ALICE", "edited", "1.1", "message_changed", "")
	if _, ok := translate(evt, testBotID); ok {
		t.Error("message with subtype should be ignored")
	}
}

func TestTranslate_IgnoresBotMessage(t *testing.T) {
	evt := messageEvent("T1", "C1", "U_X", "from a bot", "1.1", "", "B_BOT")
	if _, ok := translate(evt, testBotID); ok {
		t.Error("bot message should be ignored")
	}
}

func TestTranslate_Reaction(t *testing.T) {
	evt := socketmode.Event{
		Type: socketmode.EventTypeEventsAPI,
		Data: slackevents.EventsAPIEvent{
			TeamID: "T1",
			InnerEvent: slackevents.EventsAPIInnerEvent{
				Data: &slackevents.ReactionAddedEvent{
					User:     "U_ALICE",
					Reaction: "white_check_mark",
					Item: slackevents.Item{
						Channel:   "C1",
						Timestamp: "444.4",
					},
				},
			},
		},
	}
	got, ok := translate(evt, testBotID)
	if !ok {
		t.Fatal("reaction should be handled")
	}
	if got.Kind != KindReaction {
		t.Errorf("Kind = %v, want reaction", got.Kind)
	}
	if got.Text != "white_check_mark" {
		t.Errorf("Text = %q, want the emoji name", got.Text)
	}
	if got.Timestamp != "444.4" {
		t.Errorf("Timestamp = %q, want 444.4", got.Timestamp)
	}
}

// === translate: Slash command ==============================================

func TestTranslate_SlashCommand(t *testing.T) {
	evt := socketmode.Event{
		Type: socketmode.EventTypeSlashCommand,
		Data: slack.SlashCommand{
			TeamID:    "T1",
			ChannelID: "C1",
			UserID:    "U_ALICE",
			Command:   "/loom",
			Text:      "status",
		},
	}
	got, ok := translate(evt, testBotID)
	if !ok {
		t.Fatal("slash command should be handled")
	}
	if got.Kind != KindSlashCommand {
		t.Errorf("Kind = %v, want slash_command", got.Kind)
	}
	if got.Text != "status" {
		t.Errorf("Text = %q, want status", got.Text)
	}
}

// === translate: unhandled =================================================

func TestTranslate_IgnoresLifecycle(t *testing.T) {
	for _, et := range []socketmode.EventType{
		socketmode.EventTypeConnecting,
		socketmode.EventTypeConnected,
		socketmode.EventTypeHello,
	} {
		if _, ok := translate(socketmode.Event{Type: et}, testBotID); ok {
			t.Errorf("lifecycle event %q should be ignored", et)
		}
	}
}

// === stripMention ==========================================================

func TestStripMention(t *testing.T) {
	cases := []struct{ in, want string }{
		{"<@U07BOT> deploy", "deploy"},
		{"<@U07BOT>   spaces", "spaces"},
		{"<@U07BOT>", ""},
		{"no mention here", "no mention here"},
		{"<@OTHER> keep", "<@OTHER> keep"},
	}
	for _, c := range cases {
		if got := stripMention(c.in, testBotID); got != c.want {
			t.Errorf("stripMention(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

// === EchoHandler ===========================================================

func TestEchoHandler_Mention(t *testing.T) {
	reply, err := EchoHandler(context.Background(), Event{
		Kind: KindMention,
		Text: "deploy staging",
	})
	if err != nil {
		t.Fatalf("EchoHandler: %v", err)
	}
	if reply.Text != "echo: deploy staging" {
		t.Errorf("Text = %q, want %q", reply.Text, "echo: deploy staging")
	}
	if len(reply.React) != 1 || reply.React[0] != "eyes" {
		t.Errorf("React = %v, want [eyes]", reply.React)
	}
	if reply.Target != TargetSameThread {
		t.Errorf("Target = %v, want SameThread", reply.Target)
	}
}

func TestEchoHandler_EmptyMention(t *testing.T) {
	reply, err := EchoHandler(context.Background(), Event{Kind: KindMention, Text: "   "})
	if err != nil {
		t.Fatalf("EchoHandler: %v", err)
	}
	if reply.Text != "" {
		t.Errorf("Text = %q, want empty (ack-only)", reply.Text)
	}
	if len(reply.React) != 1 {
		t.Errorf("React = %v, want one ack reaction", reply.React)
	}
}

func TestEchoHandler_SlashCommand(t *testing.T) {
	reply, err := EchoHandler(context.Background(), Event{Kind: KindSlashCommand, Text: "status"})
	if err != nil {
		t.Fatalf("EchoHandler: %v", err)
	}
	if reply.Target != TargetEphemeral {
		t.Errorf("Target = %v, want Ephemeral", reply.Target)
	}
	if reply.Text == "" {
		t.Error("slash command reply should have text")
	}
}

func TestEchoHandler_IgnoresOther(t *testing.T) {
	for _, k := range []EventKind{KindReaction, KindFileShared, KindInteraction} {
		reply, err := EchoHandler(context.Background(), Event{Kind: k})
		if err != nil {
			t.Fatalf("EchoHandler(%v): %v", k, err)
		}
		if !reply.IsEmpty() {
			t.Errorf("EchoHandler(%v) should return empty reply, got %+v", k, reply)
		}
	}
}

// === Reply / EventKind helpers ============================================

func TestReply_IsEmpty(t *testing.T) {
	if !(Reply{}).IsEmpty() {
		t.Error("zero Reply should be empty")
	}
	if (Reply{Text: "x"}).IsEmpty() {
		t.Error("Reply with text is not empty")
	}
	if (Reply{React: []string{"eyes"}}).IsEmpty() {
		t.Error("Reply with reaction is not empty")
	}
	if (Reply{Files: []Attachment{{Name: "f"}}}).IsEmpty() {
		t.Error("Reply with file is not empty")
	}
}

func TestEventKind_String(t *testing.T) {
	cases := map[EventKind]string{
		KindMessage:      "message",
		KindMention:      "mention",
		KindSlashCommand: "slash_command",
		KindReaction:     "reaction",
		KindFileShared:   "file_shared",
		KindInteraction:  "interaction",
		KindUnknown:      "unknown",
	}
	for k, want := range cases {
		if got := k.String(); got != want {
			t.Errorf("%d.String() = %q, want %q", k, got, want)
		}
	}
}
